### ISSUE TITLE
cdnjs issue

### ISSUE THREAD

**Issue by UnrulyNatives** [idriskhenchil/Fort.js#22]
Hi. Great script - very usefull.

Problem: 

I was trying to use cdnjs: https://cdnjs.cloudflare.com/ajax/libs/Fort.js/1.0.0/fort.min.js

But if I do so, the script fails to initiate: `Uncaught ReferenceError: Fort is not defined`.
When I use .js file from the demo, everything works well!

Thx!

**Comment by idriskhenchil** [comment]
The script has now been updated to version 2.0.0. You can access it by using [here](https://cdnjs.cloudflare.com/ajax/libs/Fort.js/2.0.0/fort.js)
